// Auto-generated by Supabase. Regenerate via:
//   supabase gen types typescript --project-id tehwjoonuryqzvnotvxo > src/lib/database.types.ts
// or use the Supabase MCP `generate_typescript_types` tool.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  __InternalSupabase: { PostgrestVersion: "14.5" };
  public: {
    Tables: {
      activity_records: {
        Row: {
          available_room_nights: number | null;
          client_id: string;
          created_at: string;
          fb_covers: number | null;
          guest_nights: number | null;
          id: string;
          input_method: string;
          laundry_kg: number | null;
          notes: string | null;
          occupied_room_nights: number;
          period_end: string;
          period_start: string;
          property_id: string;
          reviewed_at: string | null;
          reviewed_by: string | null;
          status: Database["public"]["Enums"]["record_status"];
          submitted_at: string | null;
          submitted_by: string | null;
          updated_at: string;
        };
        Insert: {
          available_room_nights?: number | null;
          client_id: string;
          created_at?: string;
          fb_covers?: number | null;
          guest_nights?: number | null;
          id?: string;
          input_method?: string;
          laundry_kg?: number | null;
          notes?: string | null;
          occupied_room_nights: number;
          period_end: string;
          period_start: string;
          property_id: string;
          reviewed_at?: string | null;
          reviewed_by?: string | null;
          status?: Database["public"]["Enums"]["record_status"];
          submitted_at?: string | null;
          submitted_by?: string | null;
          updated_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["activity_records"]["Insert"]>;
        Relationships: [];
      };
      audit_log: {
        Row: {
          action: string;
          actor_id: string | null;
          actor_role: Database["public"]["Enums"]["user_role"] | null;
          client_id: string;
          created_at: string;
          id: number;
          new_data: Json | null;
          note: string | null;
          old_data: Json | null;
          property_id: string | null;
          record_id: string | null;
          table_name: string;
        };
        Insert: never;
        Update: never;
        Relationships: [];
      };
      clients: {
        Row: {
          brand: string | null;
          created_at: string;
          id: string;
          is_white_label: boolean;
          name: string;
        };
        Insert: {
          brand?: string | null;
          created_at?: string;
          id?: string;
          is_white_label?: boolean;
          name: string;
        };
        Update: Partial<Database["public"]["Tables"]["clients"]["Insert"]>;
        Relationships: [];
      };
      consumption_records: {
        Row: {
          anomaly_flags: Json;
          client_id: string;
          consumption: number;
          cost_amount: number | null;
          cost_currency: string | null;
          created_at: string;
          energy_source: Database["public"]["Enums"]["energy_source"] | null;
          id: string;
          input_method: string;
          invoice_ref: string | null;
          meter_id: string | null;
          notes: string | null;
          period_end: string;
          period_start: string;
          pillar: Database["public"]["Enums"]["pillar"];
          property_id: string;
          reviewed_at: string | null;
          reviewed_by: string | null;
          source_payload: Json | null;
          status: Database["public"]["Enums"]["record_status"];
          submitted_at: string | null;
          submitted_by: string | null;
          unit: string;
          updated_at: string;
        };
        Insert: {
          anomaly_flags?: Json;
          client_id: string;
          consumption: number;
          cost_amount?: number | null;
          cost_currency?: string | null;
          created_at?: string;
          energy_source?: Database["public"]["Enums"]["energy_source"] | null;
          id?: string;
          input_method?: string;
          invoice_ref?: string | null;
          meter_id?: string | null;
          notes?: string | null;
          period_end: string;
          period_start: string;
          pillar: Database["public"]["Enums"]["pillar"];
          property_id: string;
          reviewed_at?: string | null;
          reviewed_by?: string | null;
          source_payload?: Json | null;
          status?: Database["public"]["Enums"]["record_status"];
          submitted_at?: string | null;
          submitted_by?: string | null;
          unit: string;
          updated_at?: string;
        };
        Update: Partial<
          Database["public"]["Tables"]["consumption_records"]["Insert"]
        >;
        Relationships: [];
      };
      ef_library: {
        Row: {
          basis: string | null;
          category: string | null;
          client_id: string;
          created_at: string;
          ef_unit: string;
          ef_value: number;
          factor_key: string | null;
          id: string;
          is_active: boolean;
          notes: string | null;
          region: string | null;
          scope: number;
          source_type: Database["public"]["Enums"]["energy_source"] | null;
          standard: string | null;
          version: string;
          year: number;
        };
        Insert: {
          client_id: string;
          ef_unit: string;
          ef_value: number;
          scope: number;
          version: string;
          year: number;
          basis?: string | null;
          category?: string | null;
          created_at?: string;
          factor_key?: string | null;
          id?: string;
          is_active?: boolean;
          notes?: string | null;
          region?: string | null;
          source_type?: Database["public"]["Enums"]["energy_source"] | null;
          standard?: string | null;
        };
        Update: Partial<Database["public"]["Tables"]["ef_library"]["Insert"]>;
        Relationships: [];
      };
      emission_activities: {
        Row: {
          activity_type: string;
          anomaly_flags: Json;
          category: string | null;
          client_id: string;
          created_at: string;
          description: string | null;
          ef_id: string | null;
          ef_unit: string | null;
          ef_value: number | null;
          factor_key: string | null;
          id: string;
          input_method: string;
          invoice_ref: string | null;
          notes: string | null;
          period_end: string;
          period_start: string;
          property_id: string;
          quantity: number;
          reviewed_at: string | null;
          reviewed_by: string | null;
          scope: number;
          source_payload: Json | null;
          status: Database["public"]["Enums"]["record_status"];
          submitted_at: string | null;
          submitted_by: string | null;
          tco2e: number | null;
          tier: number | null;
          unit: string;
          updated_at: string;
          vendor: string | null;
        };
        Insert: {
          activity_type: string;
          client_id: string;
          period_end: string;
          period_start: string;
          property_id: string;
          quantity: number;
          scope: number;
          unit: string;
          anomaly_flags?: Json;
          category?: string | null;
          created_at?: string;
          description?: string | null;
          ef_id?: string | null;
          ef_unit?: string | null;
          ef_value?: number | null;
          factor_key?: string | null;
          id?: string;
          input_method?: string;
          invoice_ref?: string | null;
          notes?: string | null;
          reviewed_at?: string | null;
          reviewed_by?: string | null;
          source_payload?: Json | null;
          status?: Database["public"]["Enums"]["record_status"];
          submitted_at?: string | null;
          submitted_by?: string | null;
          tco2e?: number | null;
          tier?: number | null;
          updated_at?: string;
          vendor?: string | null;
        };
        Update: Partial<
          Database["public"]["Tables"]["emission_activities"]["Insert"]
        >;
        Relationships: [];
      };
      properties: {
        Row: {
          brand: string | null;
          city: string | null;
          client_id: string;
          country: string | null;
          created_at: string;
          currency: string;
          gfa_m2: number | null;
          id: string;
          latitude: number | null;
          longitude: number | null;
          name: string;
          region: string | null;
          rooms: number | null;
          short_name: string | null;
          status: string;
          timezone: string | null;
          type: string | null;
        };
        Insert: {
          client_id: string;
          name: string;
          brand?: string | null;
          city?: string | null;
          country?: string | null;
          created_at?: string;
          currency?: string;
          gfa_m2?: number | null;
          id?: string;
          latitude?: number | null;
          longitude?: number | null;
          region?: string | null;
          rooms?: number | null;
          short_name?: string | null;
          status?: string;
          timezone?: string | null;
          type?: string | null;
        };
        Update: Partial<Database["public"]["Tables"]["properties"]["Insert"]>;
        Relationships: [];
      };
      record_comments: {
        Row: {
          author_id: string;
          body: string;
          created_at: string;
          id: string;
          is_resolved: boolean;
          record_id: string;
        };
        Insert: {
          author_id: string;
          body: string;
          record_id: string;
          created_at?: string;
          id?: string;
          is_resolved?: boolean;
        };
        Update: Partial<
          Database["public"]["Tables"]["record_comments"]["Insert"]
        >;
        Relationships: [];
      };
      user_profiles: {
        Row: {
          client_id: string;
          created_at: string;
          email: string | null;
          full_name: string | null;
          id: string;
          role: Database["public"]["Enums"]["user_role"];
          updated_at: string;
        };
        Insert: {
          client_id: string;
          id: string;
          role: Database["public"]["Enums"]["user_role"];
          created_at?: string;
          email?: string | null;
          full_name?: string | null;
          updated_at?: string;
        };
        Update: Partial<
          Database["public"]["Tables"]["user_profiles"]["Insert"]
        >;
        Relationships: [];
      };
      user_properties: {
        Row: { property_id: string; user_id: string };
        Insert: { property_id: string; user_id: string };
        Update: Partial<Database["public"]["Tables"]["user_properties"]["Row"]>;
        Relationships: [];
      };
    };
    Views: { [_ in never]: never };
    Functions: { [_ in never]: never };
    Enums: {
      energy_source:
        | "electricity_grid"
        | "natural_gas"
        | "district_cooling"
        | "diesel"
        | "solar_pv";
      pillar: "energy" | "water" | "waste" | "carbon" | "social" | "governance";
      record_status:
        | "draft"
        | "submitted"
        | "queried"
        | "approved"
        | "rejected";
      user_role: "maker" | "checker" | "property_sm" | "super_admin";
    };
    CompositeTypes: { [_ in never]: never };
  };
};

export type Tables<T extends keyof Database["public"]["Tables"]> =
  Database["public"]["Tables"][T]["Row"];
export type Inserts<T extends keyof Database["public"]["Tables"]> =
  Database["public"]["Tables"][T]["Insert"];
export type DBEnum<T extends keyof Database["public"]["Enums"]> =
  Database["public"]["Enums"][T];
