// Auto-generated by Supabase. Regenerate via:
//   supabase gen types typescript --project-id tehwjoonuryqzvnotvxo > src/lib/database.types.ts
// or use the Supabase MCP `generate_typescript_types` tool.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  __InternalSupabase: { PostgrestVersion: "14.5" };
  public: {
    Tables: {
      audit_log: {
        Row: {
          action: string;
          actor_id: string | null;
          actor_role: Database["public"]["Enums"]["user_role"] | null;
          client_id: string;
          created_at: string;
          id: number;
          new_data: Json | null;
          note: string | null;
          old_data: Json | null;
          property_id: string | null;
          record_id: string | null;
          table_name: string;
        };
        Insert: never;
        Update: never;
        Relationships: [];
      };
      clients: {
        Row: {
          brand: string | null;
          created_at: string;
          id: string;
          is_white_label: boolean;
          name: string;
        };
        Insert: {
          brand?: string | null;
          created_at?: string;
          id?: string;
          is_white_label?: boolean;
          name: string;
        };
        Update: Partial<Database["public"]["Tables"]["clients"]["Insert"]>;
        Relationships: [];
      };
      consumption_records: {
        Row: {
          anomaly_flags: Json;
          client_id: string;
          consumption: number;
          cost_amount: number | null;
          cost_currency: string | null;
          created_at: string;
          energy_source: Database["public"]["Enums"]["energy_source"] | null;
          id: string;
          input_method: string;
          invoice_ref: string | null;
          meter_id: string | null;
          notes: string | null;
          period_end: string;
          period_start: string;
          pillar: Database["public"]["Enums"]["pillar"];
          property_id: string;
          reviewed_at: string | null;
          reviewed_by: string | null;
          source_payload: Json | null;
          status: Database["public"]["Enums"]["record_status"];
          submitted_at: string | null;
          submitted_by: string | null;
          unit: string;
          updated_at: string;
        };
        Insert: {
          anomaly_flags?: Json;
          client_id: string;
          consumption: number;
          cost_amount?: number | null;
          cost_currency?: string | null;
          created_at?: string;
          energy_source?: Database["public"]["Enums"]["energy_source"] | null;
          id?: string;
          input_method?: string;
          invoice_ref?: string | null;
          meter_id?: string | null;
          notes?: string | null;
          period_end: string;
          period_start: string;
          pillar: Database["public"]["Enums"]["pillar"];
          property_id: string;
          reviewed_at?: string | null;
          reviewed_by?: string | null;
          source_payload?: Json | null;
          status?: Database["public"]["Enums"]["record_status"];
          submitted_at?: string | null;
          submitted_by?: string | null;
          unit: string;
          updated_at?: string;
        };
        Update: Partial<
          Database["public"]["Tables"]["consumption_records"]["Insert"]
        >;
        Relationships: [];
      };
      ef_library: {
        Row: {
          client_id: string;
          created_at: string;
          ef_unit: string;
          ef_value: number;
          id: string;
          is_active: boolean;
          region: string | null;
          source_type: Database["public"]["Enums"]["energy_source"];
          version: string;
          year: number;
        };
        Insert: {
          client_id: string;
          ef_unit: string;
          ef_value: number;
          source_type: Database["public"]["Enums"]["energy_source"];
          version: string;
          year: number;
          id?: string;
          is_active?: boolean;
          region?: string | null;
          created_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["ef_library"]["Insert"]>;
        Relationships: [];
      };
      properties: {
        Row: {
          client_id: string;
          country: string | null;
          created_at: string;
          gfa_m2: number | null;
          id: string;
          latitude: number | null;
          longitude: number | null;
          name: string;
          region: string | null;
          rooms: number | null;
          status: string;
        };
        Insert: {
          client_id: string;
          name: string;
          country?: string | null;
          created_at?: string;
          gfa_m2?: number | null;
          id?: string;
          latitude?: number | null;
          longitude?: number | null;
          region?: string | null;
          rooms?: number | null;
          status?: string;
        };
        Update: Partial<Database["public"]["Tables"]["properties"]["Insert"]>;
        Relationships: [];
      };
      record_comments: {
        Row: {
          author_id: string;
          body: string;
          created_at: string;
          id: string;
          is_resolved: boolean;
          record_id: string;
        };
        Insert: {
          author_id: string;
          body: string;
          record_id: string;
          created_at?: string;
          id?: string;
          is_resolved?: boolean;
        };
        Update: Partial<
          Database["public"]["Tables"]["record_comments"]["Insert"]
        >;
        Relationships: [];
      };
      user_profiles: {
        Row: {
          client_id: string;
          created_at: string;
          email: string | null;
          full_name: string | null;
          id: string;
          role: Database["public"]["Enums"]["user_role"];
          updated_at: string;
        };
        Insert: {
          client_id: string;
          id: string;
          role: Database["public"]["Enums"]["user_role"];
          created_at?: string;
          email?: string | null;
          full_name?: string | null;
          updated_at?: string;
        };
        Update: Partial<
          Database["public"]["Tables"]["user_profiles"]["Insert"]
        >;
        Relationships: [];
      };
      user_properties: {
        Row: { property_id: string; user_id: string };
        Insert: { property_id: string; user_id: string };
        Update: Partial<Database["public"]["Tables"]["user_properties"]["Row"]>;
        Relationships: [];
      };
    };
    Views: { [_ in never]: never };
    Functions: { [_ in never]: never };
    Enums: {
      energy_source:
        | "electricity_grid"
        | "natural_gas"
        | "district_cooling"
        | "diesel"
        | "solar_pv";
      pillar: "energy" | "water" | "waste" | "carbon" | "social" | "governance";
      record_status:
        | "draft"
        | "submitted"
        | "queried"
        | "approved"
        | "rejected";
      user_role: "maker" | "checker" | "property_sm" | "super_admin";
    };
    CompositeTypes: { [_ in never]: never };
  };
};

export type Tables<T extends keyof Database["public"]["Tables"]> =
  Database["public"]["Tables"][T]["Row"];
export type Inserts<T extends keyof Database["public"]["Tables"]> =
  Database["public"]["Tables"][T]["Insert"];
export type DBEnum<T extends keyof Database["public"]["Enums"]> =
  Database["public"]["Enums"][T];
