// Auto-generated by Supabase. Regenerate via:
//   supabase gen types typescript --project-id tehwjoonuryqzvnotvxo > src/lib/database.types.ts
// or use the Supabase MCP `generate_typescript_types` tool.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  __InternalSupabase: { PostgrestVersion: "14.5" };
  public: {
    Tables: {
      activity_records: {
        Row: {
          available_room_nights: number | null;
          client_id: string;
          created_at: string;
          fb_covers: number | null;
          guest_nights: number | null;
          id: string;
          input_method: string;
          laundry_kg: number | null;
          notes: string | null;
          occupied_room_nights: number;
          period_end: string;
          period_start: string;
          property_id: string;
          reviewed_at: string | null;
          reviewed_by: string | null;
          status: Database["public"]["Enums"]["record_status"];
          submitted_at: string | null;
          submitted_by: string | null;
          updated_at: string;
        };
        Insert: {
          available_room_nights?: number | null;
          client_id: string;
          created_at?: string;
          fb_covers?: number | null;
          guest_nights?: number | null;
          id?: string;
          input_method?: string;
          laundry_kg?: number | null;
          notes?: string | null;
          occupied_room_nights: number;
          period_end: string;
          period_start: string;
          property_id: string;
          reviewed_at?: string | null;
          reviewed_by?: string | null;
          status?: Database["public"]["Enums"]["record_status"];
          submitted_at?: string | null;
          submitted_by?: string | null;
          updated_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["activity_records"]["Insert"]>;
        Relationships: [];
      };
      audit_log: {
        Row: {
          action: string;
          actor_id: string | null;
          actor_role: Database["public"]["Enums"]["user_role"] | null;
          client_id: string;
          created_at: string;
          id: number;
          new_data: Json | null;
          note: string | null;
          old_data: Json | null;
          property_id: string | null;
          record_id: string | null;
          table_name: string;
        };
        Insert: never;
        Update: never;
        Relationships: [];
      };
      clients: {
        Row: {
          brand: string | null;
          created_at: string;
          id: string;
          is_white_label: boolean;
          name: string;
        };
        Insert: {
          brand?: string | null;
          created_at?: string;
          id?: string;
          is_white_label?: boolean;
          name: string;
        };
        Update: Partial<Database["public"]["Tables"]["clients"]["Insert"]>;
        Relationships: [];
      };
      consumption_records: {
        Row: {
          anomaly_flags: Json;
          client_id: string;
          consumption: number;
          cost_amount: number | null;
          cost_currency: string | null;
          created_at: string;
          energy_source: Database["public"]["Enums"]["energy_source"] | null;
          id: string;
          input_method: string;
          invoice_ref: string | null;
          meter_id: string | null;
          notes: string | null;
          period_end: string;
          period_start: string;
          pillar: Database["public"]["Enums"]["pillar"];
          property_id: string;
          reviewed_at: string | null;
          reviewed_by: string | null;
          source_payload: Json | null;
          status: Database["public"]["Enums"]["record_status"];
          submitted_at: string | null;
          submitted_by: string | null;
          unit: string;
          updated_at: string;
        };
        Insert: {
          anomaly_flags?: Json;
          client_id: string;
          consumption: number;
          cost_amount?: number | null;
          cost_currency?: string | null;
          created_at?: string;
          energy_source?: Database["public"]["Enums"]["energy_source"] | null;
          id?: string;
          input_method?: string;
          invoice_ref?: string | null;
          meter_id?: string | null;
          notes?: string | null;
          period_end: string;
          period_start: string;
          pillar: Database["public"]["Enums"]["pillar"];
          property_id: string;
          reviewed_at?: string | null;
          reviewed_by?: string | null;
          source_payload?: Json | null;
          status?: Database["public"]["Enums"]["record_status"];
          submitted_at?: string | null;
          submitted_by?: string | null;
          unit: string;
          updated_at?: string;
        };
        Update: Partial<
          Database["public"]["Tables"]["consumption_records"]["Insert"]
        >;
        Relationships: [];
      };
      ef_datasets: {
        Row: {
          citation: string | null;
          client_id: string | null;
          currency_base_year: number | null;
          currency_code: string | null;
          gwp_set: string;
          id: string;
          imported_at: string;
          licence: string | null;
          name: string;
          notes: string | null;
          precedence: number;
          publication_year: number | null;
          publisher: string;
          source_url: string | null;
          version: string;
        };
        Insert: {
          gwp_set: string;
          name: string;
          publisher: string;
          version: string;
          citation?: string | null;
          client_id?: string | null;
          currency_base_year?: number | null;
          currency_code?: string | null;
          id?: string;
          imported_at?: string;
          licence?: string | null;
          notes?: string | null;
          precedence?: number;
          publication_year?: number | null;
          source_url?: string | null;
        };
        Update: Partial<Database["public"]["Tables"]["ef_datasets"]["Insert"]>;
        Relationships: [];
      };
      ef_factors: {
        Row: {
          activity: string;
          activity_key: string;
          boundary: string;
          boundary_note: string | null;
          category: string | null;
          client_id: string | null;
          created_at: string;
          dataset_id: string;
          domain: string;
          factor_year: number | null;
          factor_year_label: string | null;
          gas_basis: string;
          geo_code: string;
          geo_kind: string;
          geo_label: string | null;
          id: string;
          is_default: boolean;
          naics_code: string | null;
          notes: string | null;
          reliability: string | null;
          scope: number;
          source_name: string | null;
          source_url: string | null;
          status: string;
          subtype: string | null;
          unit_denominator: string;
          unit_numerator: string;
          valid_from: string | null;
          valid_to: string | null;
          value: number;
          value_biogenic: number | null;
          value_ch4: number | null;
          value_co2: number | null;
          value_n2o: number | null;
          variant: string | null;
        };
        Insert: {
          activity: string;
          activity_key: string;
          boundary: string;
          dataset_id: string;
          domain: string;
          scope: number;
          unit_denominator: string;
          value: number;
          boundary_note?: string | null;
          category?: string | null;
          client_id?: string | null;
          created_at?: string;
          factor_year?: number | null;
          factor_year_label?: string | null;
          gas_basis?: string;
          geo_code?: string;
          geo_kind?: string;
          geo_label?: string | null;
          id?: string;
          is_default?: boolean;
          naics_code?: string | null;
          notes?: string | null;
          reliability?: string | null;
          source_name?: string | null;
          source_url?: string | null;
          status?: string;
          subtype?: string | null;
          unit_numerator?: string;
          valid_from?: string | null;
          valid_to?: string | null;
          value_biogenic?: number | null;
          value_ch4?: number | null;
          value_co2?: number | null;
          value_n2o?: number | null;
          variant?: string | null;
        };
        Update: Partial<Database["public"]["Tables"]["ef_factors"]["Insert"]>;
        Relationships: [];
      };
      ef_unit_conversions: {
        Row: {
          basis: string | null;
          dataset_id: string | null;
          factor: number;
          from_unit: string;
          fuel: string | null;
          id: string;
          notes: string | null;
          to_unit: string;
          year: number | null;
        };
        Insert: {
          factor: number;
          from_unit: string;
          to_unit: string;
          basis?: string | null;
          dataset_id?: string | null;
          fuel?: string | null;
          id?: string;
          notes?: string | null;
          year?: number | null;
        };
        Update: Partial<Database["public"]["Tables"]["ef_unit_conversions"]["Insert"]>;
        Relationships: [];
      };
      ef_fx_rates: {
        Row: {
          basis: string;
          client_id: string | null;
          created_at: string;
          from_currency: string;
          id: string;
          rate: number;
          source: string | null;
          source_url: string | null;
          to_currency: string;
          year: number;
        };
        Insert: {
          from_currency: string;
          rate: number;
          year: number;
          basis?: string;
          client_id?: string | null;
          created_at?: string;
          id?: string;
          source?: string | null;
          source_url?: string | null;
          to_currency?: string;
        };
        Update: Partial<Database["public"]["Tables"]["ef_fx_rates"]["Insert"]>;
        Relationships: [];
      };
      ef_price_index: {
        Row: {
          client_id: string | null;
          created_at: string;
          id: string;
          index_value: number;
          region: string;
          series: string;
          source: string | null;
          source_url: string | null;
          year: number;
        };
        Insert: {
          index_value: number;
          series: string;
          year: number;
          client_id?: string | null;
          created_at?: string;
          id?: string;
          region?: string;
          source?: string | null;
          source_url?: string | null;
        };
        Update: Partial<Database["public"]["Tables"]["ef_price_index"]["Insert"]>;
        Relationships: [];
      };
      ef_haul_definitions: {
        Row: {
          dataset_id: string;
          haul: string;
          id: string;
          iso3: string | null;
          origin_note: string;
          territory: string;
        };
        Insert: {
          dataset_id: string;
          haul: string;
          territory: string;
          id?: string;
          iso3?: string | null;
          origin_note?: string;
        };
        Update: Partial<Database["public"]["Tables"]["ef_haul_definitions"]["Insert"]>;
        Relationships: [];
      };
      emission_activities: {
        Row: {
          activity_type: string;
          amount_original: number | null;
          anomaly_flags: Json;
          category: string | null;
          client_id: string;
          created_at: string;
          currency_original: string | null;
          deflator: number | null;
          deflator_source: string | null;
          description: string | null;
          ef_id: string | null;
          ef_unit: string | null;
          ef_value: number | null;
          factor_key: string | null;
          fx_rate: number | null;
          fx_rate_date: string | null;
          fx_source: string | null;
          id: string;
          input_method: string;
          invoice_ref: string | null;
          notes: string | null;
          period_end: string;
          period_start: string;
          price_year: number | null;
          property_id: string;
          quantity: number;
          reviewed_at: string | null;
          reviewed_by: string | null;
          scope: number;
          source_payload: Json | null;
          status: Database["public"]["Enums"]["record_status"];
          submitted_at: string | null;
          submitted_by: string | null;
          tco2e: number | null;
          tier: number | null;
          unit: string;
          updated_at: string;
          vendor: string | null;
        };
        Insert: {
          activity_type: string;
          client_id: string;
          period_end: string;
          period_start: string;
          property_id: string;
          quantity: number;
          scope: number;
          unit: string;
          amount_original?: number | null;
          anomaly_flags?: Json;
          category?: string | null;
          created_at?: string;
          currency_original?: string | null;
          deflator?: number | null;
          deflator_source?: string | null;
          description?: string | null;
          fx_rate?: number | null;
          fx_rate_date?: string | null;
          fx_source?: string | null;
          price_year?: number | null;
          ef_id?: string | null;
          ef_unit?: string | null;
          ef_value?: number | null;
          factor_key?: string | null;
          id?: string;
          input_method?: string;
          invoice_ref?: string | null;
          notes?: string | null;
          reviewed_at?: string | null;
          reviewed_by?: string | null;
          source_payload?: Json | null;
          status?: Database["public"]["Enums"]["record_status"];
          submitted_at?: string | null;
          submitted_by?: string | null;
          tco2e?: number | null;
          tier?: number | null;
          updated_at?: string;
          vendor?: string | null;
        };
        Update: Partial<
          Database["public"]["Tables"]["emission_activities"]["Insert"]
        >;
        Relationships: [];
      };
      properties: {
        Row: {
          brand: string | null;
          city: string | null;
          client_id: string;
          country: string | null;
          created_at: string;
          currency: string;
          gfa_m2: number | null;
          grid_code: string | null;
          grid_label: string | null;
          id: string;
          latitude: number | null;
          longitude: number | null;
          name: string;
          region: string | null;
          rooms: number | null;
          short_name: string | null;
          status: string;
          timezone: string | null;
          type: string | null;
        };
        Insert: {
          client_id: string;
          name: string;
          brand?: string | null;
          city?: string | null;
          country?: string | null;
          created_at?: string;
          currency?: string;
          gfa_m2?: number | null;
          grid_code?: string | null;
          grid_label?: string | null;
          id?: string;
          latitude?: number | null;
          longitude?: number | null;
          region?: string | null;
          rooms?: number | null;
          short_name?: string | null;
          status?: string;
          timezone?: string | null;
          type?: string | null;
        };
        Update: Partial<Database["public"]["Tables"]["properties"]["Insert"]>;
        Relationships: [];
      };
      record_comments: {
        Row: {
          author_id: string;
          body: string;
          created_at: string;
          id: string;
          is_resolved: boolean;
          record_id: string;
        };
        Insert: {
          author_id: string;
          body: string;
          record_id: string;
          created_at?: string;
          id?: string;
          is_resolved?: boolean;
        };
        Update: Partial<
          Database["public"]["Tables"]["record_comments"]["Insert"]
        >;
        Relationships: [];
      };
      user_profiles: {
        Row: {
          client_id: string;
          created_at: string;
          email: string | null;
          full_name: string | null;
          id: string;
          role: Database["public"]["Enums"]["user_role"];
          updated_at: string;
        };
        Insert: {
          client_id: string;
          id: string;
          role: Database["public"]["Enums"]["user_role"];
          created_at?: string;
          email?: string | null;
          full_name?: string | null;
          updated_at?: string;
        };
        Update: Partial<
          Database["public"]["Tables"]["user_profiles"]["Insert"]
        >;
        Relationships: [];
      };
      user_properties: {
        Row: { property_id: string; user_id: string };
        Insert: { property_id: string; user_id: string };
        Update: Partial<Database["public"]["Tables"]["user_properties"]["Row"]>;
        Relationships: [];
      };
    };
    Views: {
      ef_facets: {
        Row: { kind: string | null; value: string | null; factors: number | null };
        Relationships: [];
      };
    };
    Functions: { [_ in never]: never };
    Enums: {
      energy_source:
        | "electricity_grid"
        | "natural_gas"
        | "district_cooling"
        | "diesel"
        | "solar_pv";
      pillar: "energy" | "water" | "waste" | "carbon" | "social" | "governance";
      record_status:
        | "draft"
        | "submitted"
        | "queried"
        | "approved"
        | "rejected";
      user_role: "maker" | "checker" | "property_sm" | "super_admin";
    };
    CompositeTypes: { [_ in never]: never };
  };
};

export type Tables<T extends keyof Database["public"]["Tables"]> =
  Database["public"]["Tables"][T]["Row"];
export type Inserts<T extends keyof Database["public"]["Tables"]> =
  Database["public"]["Tables"][T]["Insert"];
export type DBEnum<T extends keyof Database["public"]["Enums"]> =
  Database["public"]["Enums"][T];
