import puppeteer from "puppeteer";
const sleep = (ms) => new Promise((r) => setTimeout(r, ms));
const browser = await puppeteer.launch({ headless: "new", args: ["--no-sandbox"] });
const page = await browser.newPage();
await page.setViewport({ width: 1440, height: 900 });
await page.goto("http://localhost:5173/login", { waitUntil: "networkidle0" });
await page.type("input[type=email]", "admin@demo.test");
await page.type("input[type=password]", "demo123!");
await page.click("button[type=submit]");
await page.waitForFunction(() => location.pathname !== "/login");
await sleep(1500);
await page.goto("http://localhost:5173/", { waitUntil: "networkidle0" });
await sleep(1500);
const r = await page.evaluate(() => {
  const a = document.querySelectorAll("button.card").length;
  const b = [...document.querySelectorAll("button")].filter(b => b.className?.includes("card")).length;
  return { sel: a, filter: b };
});
console.log(r);
await browser.close();
